basePath: /api/v1
consumes:
- application/json
host: localhost:8081
info:
  contact:
    email: team@workmaple.com
    name: API Support
  description: This is a sample server for a Maple Localization API.
  title: Maple Modules API
  version: "1.0"
paths:
  /:app:
    post:
      consumes:
      - application/json
      description: Pagination CreateAppWithPagination
      operationId: ApiV1LocalizationCreateAppPagination
      parameters:
      - description: WCNX0RbRD8ezrezDp9IHZ3tYdiZFb_7eu5pphTcKME8=
        in: header
        name: authorization
        type: string
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Pagination CreateApp
      tags:
      - api
  /:app/:module/:language:
    delete:
      consumes:
      - application/json
      description: Pagination DeleteLanguageWithPagination
      operationId: ApiV1LocalizationDeleteLanguagePagination
      parameters:
      - description: WCNX0RbRD8ezrezDp9IHZ3tYdiZFb_7eu5pphTcKME8=
        in: header
        name: authorization
        type: string
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Pagination DeleteLanguage
      tags:
      - api
    put:
      consumes:
      - application/json
      description: Pagination UpdateLanguageWithPagination
      operationId: ApiV1LocalizationUpdateLanguagePagination
      parameters:
      - description: WCNX0RbRD8ezrezDp9IHZ3tYdiZFb_7eu5pphTcKME8=
        in: header
        name: authorization
        type: string
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Pagination UpdateLanguage
      tags:
      - api
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
