basePath: /api/v1
consumes:
- application/json
host: localhost:8081
info:
  contact:
    email: team@workmaple.com
    name: API Support
  description: This is a sample server for a Maple Localization API.
  title: Maple Modules API
  version: "1.0"
paths:
  /:app:
    delete:
      consumes:
      - application/json
      description: DeleteApp
      operationId: Localization_DeleteApp
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: DeleteApp
      tags:
      - APP
    get:
      consumes:
      - application/json
      description: ReadApp
      operationId: Localization_ReadApp
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: ReadApp
      tags:
      - APP
    post:
      consumes:
      - application/json
      description: CreateApp
      operationId: Localization_CreateApp
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: CreateApp
      tags:
      - APP
    put:
      consumes:
      - application/json
      description: UpdateApp
      operationId: Localization_UpdateApp
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: UpdateApp
      tags:
      - APP
  /:app/:module:
    delete:
      consumes:
      - application/json
      description: DeleteModule
      operationId: Localization_DeleteModule
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: DeleteModule
      tags:
      - APP/MODULE
    get:
      consumes:
      - application/json
      description: ReadModule
      operationId: Localization_ReadModule
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: ReadModule
      tags:
      - APP/MODULE
    post:
      consumes:
      - application/json
      description: CreateModule
      operationId: Localization_CreateModule
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: CreateModule
      tags:
      - APP/MODULE
    put:
      consumes:
      - application/json
      description: UpdateModule
      operationId: Localization_UpdateModule
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: UpdateModule
      tags:
      - APP/MODULE
  /:app/:module/:language:
    delete:
      consumes:
      - application/json
      description: DeleteLanguage
      operationId: Localization_DeleteLanguage
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: DeleteLanguage
      tags:
      - APP/MODULE/LANGUAGE
    get:
      consumes:
      - application/json
      description: ReadLanguage
      operationId: Localization_ReadLanguage
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: ReadLanguage
      tags:
      - APP/MODULE/LANGUAGE
    post:
      consumes:
      - application/json
      description: CreateLanguage
      operationId: Localization_CreateLanguage
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: CreateLanguage
      tags:
      - APP/MODULE/LANGUAGE
    put:
      consumes:
      - application/json
      description: UpdateLanguage
      operationId: Localization_UpdateLanguage
      parameters:
      - description: app
        in: body
        name: app
        required: true
        schema:
          type: string
      - description: module
        in: body
        name: module
        required: true
        schema:
          type: string
      - description: language
        in: body
        name: language
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: UpdateLanguage
      tags:
      - APP/MODULE/LANGUAGE
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
